packages:
    - packages/*

allowBuilds:
    esbuild: true

overrides:
    "@eslint/plugin-kit@<0.3.4": ">=0.3.4"

peerDependencyRules:
    ignoreMissing:
        - eslint-plugin-import
        - eslint

allowedDeprecatedVersions:
    source-map-resolve: "*"
    resolve-url: "*"
    source-map-url: "*"
    urix: "*"
    q: "*"
